baseURL: "https://yashlamba.github.io/"
title: "Yash Lamba"
paginate: 5
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
# buildFuture: false
# buildExpired: false

googleAnalytics: UA-154810488-1

minify:
  disableXML: true
  # minifyOutput: true

languageName: "English"

outputs:
  home:
    - HTML
    - RSS
    - JSON

title: home/
menu:
  main:
    - name: About
      url: about
      weight: 1
    - name: Blog
      url: blogs/
      weight: 3
    # - name: Projects
    #   url: projects/
    #   weight: 2
    - name: Tags
      url: tags
      weight: 4
    - name: Resume
      url: Resume_YashLamba.pdf

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Yash Lamba - Portfolio"
  author: Yash Lamba
  # author: ["Me", "You"] # multiple authors
  
  profileMode:
    enabled: true
    title: Yash Lamba
    # imageUrl: "#"
    # imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    subtitle: "Software developer | Engineering Junior | Educator"
    buttons:
      - name: Blog
        url: posts
      - name: Projects
        url: projects

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true

  socialIcons:
    - name: github
      url: "https://github.com/yashlamba"
    - name: linkedin
      url: "https://linkedin.com/in/yl1"
    - name: email
      url: "mailto:yashlamba2000@gmail.com"

  # label:
  #   text: "Home"
  #   icon: icon.png
  #   iconHeight: 35

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  # assets:
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]

taxonomies:
  tag: tags

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

