baseURL: "https://yashlamba.com/"
theme: papermod
pagination:
  pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false

googleAnalytics: G-3MTKQ1LJNX

minify:
  disableXML: true

copyright: "&copy; 2025 Yash Lamba"

languageName: "English"

outputs:
  home:
    - HTML
    - RSS
    - JSON

title: home/
menu:
  main:
    - name: about/
      url: about
      weight: 1
    - name: blog/
      url: blogs/
      weight: 3
    - name: projects/
      url: projects/
      weight: 2
    - name: search/
      url: search

params:
  env: production
  description: "Portfolio of Yash Lamba - Working as Software Engineer at CERN on Zenodo and InvenioRDM projects. Explore the website for learn more about Yash, blogs etc."
  author: Yash Lamba
  images: ["images/social_preview.png"]

  profileMode:
    enabled: true
    title: Yash Lamba
    subtitle: "Software Developer with a knack for teaching!"
    buttons:
      - name: Resume
        url: Resume_YashLamba.pdf
      - name: Tags
        url: tags
      - name: Explore
        url: explore

  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true

  socialIcons:
    - name: github
      url: "https://github.com/yashlamba"
    - name: linkedin
      url: "https://linkedin.com/in/yl1"
    - name: email
      url: "mailto:contact@yashlamba.com"
    - name: youtube
      url: "https://www.youtube.com/@whereisyash"

  # label:
  #   text: "Home"
  #   icon: icon.png
  #   iconHeight: 35

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  # assets:
  #   favicon: "<link / abs url>"
  #   favicon16x16: "<link / abs url>"
  #   favicon32x32: "<link / abs url>"
  #   apple_touch_icon: "<link / abs url>"
  #   safari_pinned_tab: "<link / abs url>"

  # cover:
  #   hidden: true # hide everywhere but not in structured data
  #   hiddenInList: true # hide on list pages and home
  #   hiddenInSingle: true # hide on single page

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

taxonomies:
  tag: tags

markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        # guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true

